name: Prepare For GitHub Release

on:
  [push]

jobs:
  build_release_win64:
    name: Release for Windows x64
    runs-on: windows-2019
    steps:
      - name: Checkout Sources
        uses: actions/checkout@master
        with:
          ref: master
      - name: Restore Git Submodules
        run: git submodule update --init
# --------------------------------------------------------
      - name: Installing aqtinstall
        run: pip3 install aqtinstall

      - name: Install Qt
        run: python -m aqt install 5.12.5 windows desktop win64_mingw73
# --------------------------------------------------------
      - name: Build Qv2ray
        run: |
          mkdir build
          cd build
          set PATH=..\Qt5.12.5\5.12.5\mingw73_64\bin;..\Qt5.12.5\Tools\mingw73_64\bin;%PATH%
          qmake ..
          mingw32-make -j4

  build_release_linux:
    name: Release for linux
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Sources
        uses: actions/checkout@master
        with:
          ref: master
      - name: Restore Git Submodules
        run: git submodule update --init
# --------------------------------------------------------
      - name: Installing Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: "Preparing NPM"
        run: | 
          cd .github/install-qt/
          npm ci
          npm run build

      - name: Install Qt
        uses: ./.github/install-qt/
# --------------------------------------------------------
      - name: Install libgl-dev
        run: sudo apt install -y libgl-dev
      - name: Build Qv2ray
        run: |
          mkdir build
          cd build
          qmake ..
          make -j4

  build_release_macOS:
    name: Release for macOS
    runs-on: macOS-10.14
    steps:
      - name: Checkout Sources
        uses: actions/checkout@master
        with:
          ref: master
      - name: Restore Git Submodules
        run: git submodule update --init
# --------------------------------------------------------
      - name: Installing Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: "Preparing NPM"
        run: | 
          cd .github/install-qt/
          npm ci
          npm run build

      - name: Install Qt
        uses: ./.github/install-qt/
# --------------------------------------------------------
      - name: Build Qv2ray
        run: |
          mkdir build
          cd build
          qmake ..
          make -j4
